unify manual and credential chain credentials
aws/aws-sigv4-auth-cassandra-nodejs-driver-plugin pull request #5
Opened 2020-12-17 17:25 UTC by JoshRagem

removed a credential resolution function that always returned undefined
fetch (potentially cached) credentials when needed--at the challange

*Issue #, if available:* https://github.com/aws/aws-sigv4-auth-cassandra-nodejs-driver-plugin/issues/4

*Description of changes:* brings the manually submitted credentials and the default credentials onto the same level by leveraging `AWS.CredentialProviderChain` which will manage all issues of credential caching and retrieval for default (or externally configured) credential providers. added appropriate tests

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-12-18 20:09 UTC, bhouse99 requested changes
Thanks so much for your contribution!

One minor thing, could you increment the CHANGELOG.md  and include a short description of the change? 
Thanks!

2020-12-21 14:01 UTC, JoshRagem commented
@bhouse99 no problem, is `1.0.3` the next version you want?

2020-12-23 18:03 UTC, merged

2020-12-23 18:03 UTC, bhouse99 commented
I tested this against different configs, and I think I'll just merge in the branch and update the changes myself.  :).  Again thanks!

2021-09-03 13:50 UTC, rizblie commented
Any reason why hasn't this version been released on npm?